# Generated by Django 6.0 on 2026-09-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('contri_name', models.CharField(max_length=100)),
                ('contri_roll', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('contri_skill', models.CharField(default='Not Specified', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=1)),
                ('phone', models.CharField(default='', max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('portfolio', models.CharField(max_length=100)),
                ('joining_details', models.CharField(max_length=100)),
            ],
        ),
    ]
